version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: flyingfox
      POSTGRES_USER: fox
      POSTGRES_DB: covid
    ports:
      - "5500:5432"
    volumes:
       - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
