version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: flyingfox
      POSTGRES_USER: fox
      POSTGRES_DB: covid
    ports:
      - "5500:5432"
    volumes:
       - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080

  python:
    build: ./build/Dockerfile_py
    depends_on:
      - db
    environment:
      db_username: fox
      db_password: flyingfox
      db_host: db
      db_port: 5432
      db_name: covid

  hospital:
    build: ./build/Dockerfile_hospital
    depends_on:
      - db
    environment:
      db_username: fox
      db_password: flyingfox
      db_host: db
      db_port: 5432
      db_name: covid

  pcr:
    build: ./build/Dockerfile_pcr
    depends_on:
      - db
    environment:
      db_username: fox
      db_password: flyingfox
      db_host: db
      db_port: 5432
      db_name: covid

volumes:
  dbdata:
