######## Builder ########
FROM rust:1 as builder
ENV APP_PATH=pcr
RUN USER=root cargo new --bin pcr

# copy dependency
COPY ./db ./db
COPY ./utils ./utils
COPY ./proto ./proto
COPY ./pcr ${APP_PATH}
# copy lock
COPY ./Cargo.lock ${APP_PATH}

# Install rustfmt
RUN rustup component add rustfmt

WORKDIR ${APP_PATH}

# build
RUN cargo build --release

######## Runner ########
FROM debian:bullseye
ARG APP=/usr/src/app

RUN apt-get purge ca-certificates
RUN apt-get update && apt-get install -y openssl \
    ca-certificates \
    wget \
    procps

# RUN useradd ferris

COPY --from=builder /pcr/target/release/pcr ${APP}/pcr

WORKDIR ${APP}

RUN GRPC_HEALTH_PROBE_VERSION=v0.4.6 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

# USER ferris

CMD ["./pcr"]
