######## Builder ########
FROM rust:1 as builder
ENV APP_PATH=hospital
RUN USER=root cargo new --bin hospital

# copy dependency
COPY ./db ./db
COPY ./utils ./utils
COPY ./proto ./proto

# Install rustfmt
RUN rustup component add rustfmt

WORKDIR ${APP_PATH}

# copy toml
COPY ./hospital/Cargo.toml ${APP_PATH}
COPY ./Cargo.lock ${APP_PATH}

# build
RUN cargo build --release
RUN rm src/*.rs

# Use the code to compile the project w/o having to redownload the dependency
COPY ./hospital/* ${APP_PATH}
RUN ls
RUN rm ./target/release/deps/hospital*
RUN cargo build --release

######## Runner ########
FROM debian:bullseye
ARG APP=/usr/src/app

RUN apt-get purge ca-certificates
RUN apt-get update && apt-get install -y openssl \
    ca-certificates \
    wget

RUN useradd ferris

COPY --from=builder /hospital/target/release/hospital ${APP}/hospital

# install grpc_health_probe
RUN GRPC_HEALTH_PROBE_VERSION=v0.4.6 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

WORKDIR ${APP}

USER ferris

CMD ["./hospital"]
