name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hospital:
    uses: shigedangao/mask/.github/workflows/reusable-build-image.yaml@main
    with:
      file_path: Dockerfile_hospital
      image_name: mask_hospital
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account_name: ${{ secrets.SERVICE_ACCOUNT_NAME }}
  pcr:
    uses: shigedangao/mask/.github/workflows/reusable-build-image.yaml@main
    with:
      file_path: Dockerfile_pcr
      image_name: mask_pcr
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account_name: ${{ secrets.SERVICE_ACCOUNT_NAME }}

  python:
    uses: shigedangao/mask/.github/workflows/reusable-build-image.yaml@main
    with:
      file_path: Dockerfile_py
      image_name: mask_python
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account_name: ${{ secrets.SERVICE_ACCOUNT_NAME }}
