on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      file_path:
        required: true
        type: string
    secrets:
      workload_identity_provider:
        required: true
      service_account_name:
        required: true  

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - name: authenticate with gcloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_name }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Build docker image
        run: |-
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          gcloud builds submit \
            --substitutions=_LOCATION="europe-west1",_REPOSITORY="rusty",_IMAGE=${{ inputs.image_name }},_SHA=$git_hash,_DOCKERFILE=${{ inputs.file_path }}
