on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true  

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.docker_username }}/${{ inputs.image_name }}
          tags: |
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Github sha
        run: echo "SHA=${GITHUB_SHA}" >> $GITHUB_ENV
        shell: bash
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .build/${{ inputs.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
